#mysql
spring:
   datasource:
      url: jdbc:mysql://120.77.148.235:3306/banxue-dev?useUnicode=true&characterEncoding=utf8
      username: feng
      password: feng.123456
      driver-class-name: com.mysql.jdbc.Driver
# server
server:
    port: 8084
data:
   name: 21
HeadUrlHead: http://127.0.0.1:8085/user/getHead?headName=