#mysql
spring:
   datasource:
      url: jdbc:mysql://172.18.221.80:3306/banxue-dev?useUnicode=true&characterEncoding=utf8
      username: feng
      password: feng.123456
      driver-class-name: com.mysql.jdbc.Driver
# server
server:
    port: 80
data:
   name: 21
HeadUrlHead: http://www.yunhong66.com:8085/user/getHead?headName=