#mybatis-plus
mybatis-plus:
   mapper-locations: com/banxue/*/mapper/xml/*.xml
   type-aliases-package: com.banxue.*.entity
spring:
   jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
   profiles:
      active: dev
# server
server:
    port: 8085
data:
   name: 21
callBaseUrl: https://apppro.cloopen.com:8883/2013-12-26